name = "codecrafters_redis"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_otp = "~> 0.10"
glisten = ">= 7.0.1 and < 8.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
clad = ">= 1.1.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
file_streams = ">= 1.6.0 and < 2.0.0"
mug = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
